menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: 'Schleichstrasse 4 72076 Tübingen Germany', phone: '', email: 'tolgahan7008@gmail.com', office: '', image: 'assets/img/contact.png', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/tolgahan-aydin'}
- {icon: 'twitter', link: ''}
- {icon: 'instagram', link: ''}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/tolgahan-aydin/'}

contacts:
- {name: 'Tolgahan Aydın', title: 'M.A.', department: 'Cognitive Psychology', institution: 'Tübingen University', institution_address: 'Schleichstrasse 4 72076 Tübingen Germany', phone: '', email: 'tolgahan7008@gmail.com', office: '', image: 'assets/img/contact.png'}
