menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'certificates', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Primary Investigator', title: 'Professor', department: 'Cognitive Psychology', institution: '', institution_address: '', phone: '', email: '', office: '', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Cognitive Psychology', institution: '', institution_address: '', phone: '', email: '', office: '', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Cognitive Psychology', institution: '', institution_address: '', phone: '', email: '', office: '', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Improving your statistical inferences', url: 'Improving your statistical inferences'}
- {name: 'Inferential Statistics', url: 'Inferential Statistics'}
- {name: 'Introduction to the Tidyverse', url: 'Introduction to the Tidyverse'}
- {name: 'Importing Data in the Tidyverse', url: 'Importing Data in the Tidyverse'}
- {name: 'Wrangling Data in the Tidyverse', url: 'Wrangling Data in the Tidyverse'}
- {name: 'Visualizing Data in the Tidyverse', url: 'Visualizing Data in the Tidyverse'}

social:
- {icon: 'github', link: 'https://github.com/tolgahan-aydin'}
- {icon: 'orcid', link: 'https://orcid.org/0000-0002-0747-6584'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/tolgahan-aydin/'}

contacts:
- {name: 'Tolgahan Aydın', title: 'M.A.', department: 'Cognitive Psychology', institution: 'Tübingen University', institution_address: 'Schleichstrasse 4 72076 Tübingen Germany', phone: '', email: 'tolgahan7008@gmail.com', office: '', image: 'assets/img/contact.png'}
